<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ChatGPT Image Sep 23, 2025, 12_12_28 PM (1).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ChatGPT Image Sep 23, 2025, 12_12_28 PM (1).ico" />
  </ItemGroup>


</Project>
